---
- name: manage users
  ansible.builtin.include_tasks: users.yml

- name: manage ssh host keys
  ansible.builtin.include_tasks: keys.yml

- name: Insert banner
  ansible.builtin.copy:
    content: |
     WARNING: Unauthorized access to this system is forbidden and will be
     prosecuted by law. By accessing this system, you agree that your actions
     may be monitored if unauthorized usage is suspected.
    dest: /etc/issue.net
    mode: 'u=rw,g=r,o=r'

- name: Create sshd configuration
  become: true
  ansible.builtin.template:
    src: 'templates/sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
    validate: /usr/sbin/sshd -t -f %s
    backup: true
  notify:
    - restart ssh

- name: Ensure SSH is started and enabled at boot
  ansible.builtin.service:
    name: "{{ role_ssh_service_name }}"
    state: "{{ role_ssh_service_state }}"
    enabled: "{{ role_ssh_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure handlers are notified now to avoid firewall conflicts
  ansible.builtin.meta: flush_handlers
