---
- name: Create group for missing ssh users
  ansible.builtin.group:
    name: '{{ item.key }}'
    state: present
  with_dict: "{{ role_ssh_users }}"

- name: Create missing ssh users
  ansible.builtin.user:
    name: '{{ item.key }}'
    group: '{{ item.key }}'
  with_dict: "{{ role_ssh_users }}"

- name: Set permissions for .ssh directory
  ansible.builtin.file:
    path: "/home/{{ item.key }}/.ssh"
    state: directory
    mode: 0700
    owner: "{{ item.key }}"
    group: "{{ item.key if ansible_os_family != 'Suse' else 'users' }}"
  with_dict: "{{ role_ssh_users }}"

- name: Insert public ssh key for users
  ansible.builtin.blockinfile:
    dest: "/home/{{ item.key }}/.ssh/authorized_keys"
    create: true
    owner: "{{ item.key }}"
    group: "{{ item.key if ansible_os_family != 'Suse' else 'users' }}"
    mode: 0600
    block: "{{ item.value.key }}"
  with_dict: "{{ role_ssh_users }}"

- name: Add configured user accounts to passwordless sudoers.
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ role_ssh_sudoers_passwordless }}"
  when: role_ssh_sudoers_passwordless | length > 0

- name: Add configured user accounts to passworded sudoers.
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ item }}'
    line: '{{ item }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0440
  with_items: "{{ role_ssh_sudoers_passworded }}"
  when: role_ssh_sudoers_passworded | length > 0
